import { VerticalBox, LineEdit, Button, HorizontalBox } from "std-widgets.slint";
export component Login inherits Window {
    title: "FBLA Finance Login";
    background: black;
    in-out property <string> username;
    in-out property <string> password;
    callback login-pressed <=> login.clicked;
    callback signup-pressed <=> signup.clicked;
    HorizontalBox {
        width: 100%;
        VerticalBox {
            alignment: LayoutAlignment.center;
            spacing: 1rem;
            min-width: 20rem;
            
            Text {
                text: "Login";
                horizontal-alignment: center;
                font-size: 3rem;
                color: white;
            }
            LineEdit {
                input-type: InputType.text;
                placeholder-text: "username";
                font-size: 3rem;
                text <=> root.username;
            }
            LineEdit {
                input-type: InputType.password;
                placeholder-text: "password";
                font-size: 3rem;
                text <=> root.password;
            }
            login := Button {
                primary: true;
                text: "Login";
            }
            signup := Button {
                text: "Sign Up";
            }
        }
    }
}

export component SignUp inherits Window {
    title: "FBLA Finance Sign Up";
    background: black;
    in-out property <string> username;
    in-out property <string> password;
    callback signup-pressed <=> signup.clicked;
    callback login-pressed <=> login.clicked;
    
    VerticalBox {
        alignment: LayoutAlignment.center;
        spacing: 1rem;
        padding: 10rem;
        Text {
            text: "Sign Up";
            horizontal-alignment: center;
            font-size: 3rem;
            color: white;
        }
        LineEdit {
            input-type: InputType.text;
            placeholder-text: "username";
            font-size: 3rem;
            text <=> root.username;
        }
        LineEdit {
            input-type: InputType.password;
            placeholder-text: "password";
            font-size: 3rem;
            text <=> root.password;
        }
        signup := Button {
            primary: true;
            text: "Sign Up";
        }
        login := Button {
            text: "Login";
        }
    }
}

export component Home inherits Window {
    title: "FBLA Finance App";
    in-out property <string> username;
    Text {
        text: "Logged in as, "+username;
        horizontal-alignment: center;
        font-size: 3rem;
        // color: white;
    }
}